In [1]:
import numpy as np
from math import sqrt
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
background = np.loadtxt("background.txt")
signal = np.loadtxt("signal.txt")

In [20]:
merged = np.concatenate((signal, background))
rows, cols = signal.shape
n = rows
mu = np.mean(merged)
sigma = np.std(merged)
mean_s = np.mean(signal, axis=0)
mean_b = np.mean(background, axis=0)
fisher = n*((mean_s-mu)**2+(mean_b-mu)**2)/sigma**2
print(fisher)


[ 1143.35565056  1164.7431085   3249.63259108  3272.70276118
 94813.227569    3506.062678    3589.58343959]


In [27]:
print(merged.shape)
print(signal.shape)
print(background[0,:])

(20000, 7)
(10000, 7)
[2.14802844e+02 2.97257569e+02 1.05432714e+00 1.58281937e+01
 4.47392260e+03 1.44019512e+01 3.04446727e-01]


In [60]:
index = np.flip(fisher.argsort(axis=0))
print(fisher)
print(index)
np.take_along_axis(fisher, index, axis=0) 


[ 1143.35565056  1164.7431085   3249.63259108  3272.70276118
 94813.227569    3506.062678    3589.58343959]
[4 6 5 3 2 1 0]


array([94813.227569  ,  3589.58343959,  3506.062678  ,  3272.70276118,
        3249.63259108,  1164.7431085 ,  1143.35565056])

In [39]:
np.flip(index)

array([4, 6, 5, 3, 2, 1, 0])

In [90]:
index2 = np.repeat(np.atleast_2d(index),10000, axis=0)
ranked_signal = np.take_along_axis(signal, index2, axis=1)[0]
ranked_background = np.take_along_axis(background, index2, axis=1)[0]

In [89]:
print(background[0,:])
print(np.take_along_axis(background[0,:], index, axis=0))
np.take_along_axis(background, index2, axis=1)[0]

[2.14802844e+02 2.97257569e+02 1.05432714e+00 1.58281937e+01
 4.47392260e+03 1.44019512e+01 3.04446727e-01]
[4.47392260e+03 3.04446727e-01 1.44019512e+01 1.58281937e+01
 1.05432714e+00 2.97257569e+02 2.14802844e+02]


array([4.47392260e+03, 3.04446727e-01, 1.44019512e+01, 1.58281937e+01,
       1.05432714e+00, 2.97257569e+02, 2.14802844e+02])

In [47]:
ranked_signal = np.take_along_axis(signal, index, axis=0)


ValueError: `indices` and `arr` must have the same number of dimensions

In [41]:
n = ["f0", "f1", "f2", "f3", "f4", "f5", "f6"]
nm = np.asarray(n)
np.take_along_axis(nm, index, axis=0)

array(['f4', 'f6', 'f5', 'f3', 'f2', 'f1', 'f0'], dtype='<U2')